app {
  kafka {
    bootstrap-server = "localhost:9092"
  }
  database {
    url = ""
    username = ""
    username = ${?database.username}
    password = ""
    password = ${?database.password}
  }
}