addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("org.typelevel"         % "sbt-tpolecat"        % "0.5.0")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"          % "7.4.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-git"             % "1.0.1")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.10.0")
