name: Scala

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@21.0.0
# todo enable after adding kafka and tests
#      - name: "Starting up Docker 🐳"
#        run: docker-compose up -d

#      - name: Tests
#        run: sbt 'test;it:test'

#      - name: "Shutting down Docker 🐳"
#        run: docker-compose down